### ISSUE TITLE
`--fork` does not wait until the fork is actually completed

### ISSUE THREAD

**Issue by siketyan** [siketyan/ghr#128]

**Comment by yu-ichiro** [comment]
Additional Information:
GitHub's fork process is ran asynchronously, and there are no means to check the status programmatically.
https://docs.github.com/en/rest/repos/forks?apiVersion=2022-11-28#:~:text=Note%3A%20Forking%20a%20Repository%20happens%20asynchronously.%20You%20may%20have%20to%20wait%20a%20short%20period%20of%20time%20before%20you%20can%20access%20the%20git%20objects.%20If%20this%20takes%20longer%20than%205%20minutes%2C%20be%20sure%20to%20contact%20GitHub%20Support.
https://stackoverflow.com/questions/33666838/determine-if-a-fork-is-ready

[gh](https://github.com/cli/cli) retries 3 times every 2 seconds

https://github.com/cli/cli/blob/trunk/pkg/cmd/repo/fork/fork.go#L333-L344
